### ISSUE TITLE
centreon integration

### ISSUE THREAD

**Issue by ghost** [elsamuko/clusterup#2]
Hi @elsamuko ,

Hope you are all well !

I want to start a quiet similar project to yours with centreon. 

Do you think that we can add this layer of monitoring to clusterup ? or shall I start a another app ?

Thanks for any insights or inputs on that :-)

Cheers,
Luc Michalski

**Comment by elsamuko** [comment]
Honestly, I don't know.
clusterup wasn't build with a big architecture or extendibility in my mind, it's for me to learn some flutter.
